package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.Button;

import javafx.scene.control.TextField;

import java.net.URL;
import java.util.ResourceBundle;

import businessLogic.User;
import javafx.event.ActionEvent;

import javafx.scene.control.PasswordField;

public class MyAccountController implements Initializable {
	@FXML
	private Button delete;
	@FXML
	private TextField username;
	@FXML
	private PasswordField password;
	@FXML
	private TextField firstname;
	@FXML
	private TextField lastname;

	public void setUsername(String username) {
		this.username.setText(username);
	}

	public void setPassword(String password) {
		this.password.setText(password);
	}

	public void setFirstname(String firstname) {
		this.firstname.setText(firstname);
	}

	public void setLastname(String lastname) {
		this.lastname.setText(lastname);
	}

	// Event Listener on Button[#delete].onAction
	@FXML
	public void delete(ActionEvent event) {
		// TODO Autogenerated
	}

	public void setAllUserInfo() {

		User user = User.getSession();

		this.setUsername(user.getUsername());
		this.setPassword(user.getPassword());
		this.setFirstname(user.getFirstname());
		this.setLastname(user.getLastname());

	}

	@Override
	public void initialize(URL location, ResourceBundle resources) {

		this.setAllUserInfo();
	}
}
