package controller;

import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.text.Text;

import java.net.URL;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.ResourceBundle;

import businessLogic.Recipe;
import businessLogic.User;
import facade.RecipeFacade;
import javafx.collections.FXCollections;
import javafx.collections.ObservableList;
import javafx.event.ActionEvent;

import javafx.scene.control.ComboBox;

import javafx.scene.input.MouseEvent;

import javafx.scene.control.TableView;
import javafx.scene.control.cell.PropertyValueFactory;
import javafx.scene.control.TableColumn;

public class QuickSearchController implements Initializable {
	@FXML
	private TableView<Recipe> listRecipes;
	@FXML
	private TableColumn<Recipe, String> recipeName;
	@FXML
	private TableColumn<Recipe, String> rating;
	@FXML
	private TableColumn<Recipe, Integer> preparationTime;
	@FXML
	private TableColumn<Recipe, Integer> difficulty;
	@FXML
	private ComboBox<String> filter;
	@FXML
	private Text nbResult;
	
	private ArrayList<Recipe> results = new ArrayList<Recipe>();

	private RecipeFacade facade = RecipeFacade.getInstance();
	
	public void setListRecipes(TableView listRecipes) {
		this.listRecipes = listRecipes;
	}
	public void setRecipeName(TableColumn recipeName) {
		this.recipeName = recipeName;
	}
	public void setRating(TableColumn rating) {
		this.rating = rating;
	}
	public void setPreparationTime(TableColumn preparationTime) {
		this.preparationTime = preparationTime;
	}
	public void setDifficulty(TableColumn difficulty) {
		this.difficulty = difficulty;
	}
	public void setFilter(ComboBox filter) {
		this.filter = filter;
	}
	public void setNbResult(Text nbResult) {
		this.nbResult = nbResult;
	}
	public void setResults(ArrayList<Recipe> results) {
		this.results = results;
	}

	public void setResultsInTableView() {
		listRecipes.setItems(FXCollections.observableArrayList(results));
	}
	
	public void setCourseCategoryFilter() {

		HashMap<Integer, String> courses = facade.findAllCourseCategory();
		ObservableList<String> choices = FXCollections.observableArrayList(courses.values());
		choices.add(0, "all recipes");
		filter.setItems(choices);
	}
	
	// Event Listener on TableView[#listRecipes].onMousePressed
	@FXML
	public void consultRecipe(MouseEvent event) {
		// TODO Autogenerated
	}
	// Event Listener on ComboBox[#filter].onAction
	@FXML
	public void filterRecipesByCourseCategory(ActionEvent event) {
		// TODO Autogenerated
	}
	@Override
	public void initialize(URL location, ResourceBundle resources) {

		recipeName.setCellValueFactory(new PropertyValueFactory<Recipe, String>("nameRecipe"));
		// rating.setCellValueFactory(new PropertyValueFactory<Recipe, String>(""));
		preparationTime.setCellValueFactory(new PropertyValueFactory("preparationTime"));
		difficulty.setCellValueFactory(new PropertyValueFactory("difficulty"));

		setCourseCategoryFilter();
		
	}
}
